name: Main

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write

jobs:
  # Always run checks
  checks:
    name: Checks
    uses: ./.github/workflows/reusable_checks.yml
    secrets: inherit

  # Release Please to create releases
  release:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      # fromJSON to convert string "true"/"false" to boolean - doesn't match what's in release-please docs
      # https://github.com/googleapis/release-please-action/issues/912#issuecomment-2024459449
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}

  # Upload wheels if a release was created
  upload:
    name: Upload
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.release.outputs.releases_created) }}
    environment: 
      name: pypi
      url: https://pypi.org/p/bor2mqtt
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Build Wheels
        run: uv build
      
      # upload to pypi
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Pypi

      # upload to GitHub Release
      - name: Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
        run: gh release upload -R ${{ github.repository }} ${{ needs.release.outputs.tag_name }} ./dist/*
