name: "General checks: Lints, Tests, Docs"

on:
  workflow_call:

jobs:
  # check python formatting
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/ruff-action@v3
        name: Ruff

  # check python typing
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --dev --verbose --all-extras
      - name: Run basedpyright
        run: uv run basedpyright